apiVersion: v1
kind: Service
metadata:
  name: backend-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
